// The Lens Designer consumer runtime, shipped as two Lens Studio TypeScript
// assets written into `Assets/LensDesigner/` on attach (same pattern as the
// state controller — see state-controller.ts):
//
//   1. `LensDesigner.ts` — the consumer-facing helper module (backlog item 1,
//      option A decided 2026-06-02). Lenses import it and call granular
//      helpers: bay show/hide, posture swaps, and `whenReady` (the
//      spawn-and-populate poll every consumer was hand-rolling — backlog 7).
//
//   2. `LDRuntimeGate.ts` — a tiny @component the bridge attaches to BOTH bay
//      roots (backlog 3). On a real device (`!isEditor()`) it forces runtime
//      posture at lens start — edit bay hidden, app bay shown — even if the
//      project was last saved mid-design-session (crash, force-quit). Inside
//      the editor it's a no-op: the designer (or the designer-off toggle)
//      owns the posture there. Attached to both bays because either one may
//      be the enabled one in a saved scene — whichever is on runs the gate.
//
// Stored as strings (not real TS in src/) because the bodies use LS ambient
// globals (@component, BaseScriptComponent, global.scene, print) that the
// bridge's own tsc can't resolve. LS owns the compile; we validate via the
// LS-side compile, not the bridge's tsc.
//
// LS 5.15.4 APIs used (verified against the on-disk declarations 2026-06-08):
//   - global.scene.getRootObjectsCount() / getRootObject(i)  (StudioLib.d.ts)
//   - global.deviceInfoSystem.isEditor(): boolean            (StudioLib.d.ts)
//   - SceneObject.enabled / .name
//
// IMPORTANT: no backticks or dollar-brace sequences inside the emitted
// bodies — they live inside template literals here (the CoverView codegen
// regression taught us this the hard way).

/** Names of the two designer-owned scene roots. Must mirror connection.ts. */
export const EDIT_BAY_NAME = '__LensDesignerEditBay__';
export const APP_BAY_NAME = '__LensDesignerAppBay__';

export const LD_RUNTIME_MODULE_FILENAME = 'LensDesigner.ts';
export const LD_RUNTIME_GATE_FILENAME = 'LDRuntimeGate.ts';

export const LD_RUNTIME_MODULE_SRC = `// LensDesigner runtime helpers (generated by Lens Designer - do not edit).
//
// Consumer API for lenses built with Lens Designer:
//
//   import { LensDesigner } from './LensDesigner/LensDesigner';
//
//   LensDesigner.hideEditBay();      // hide the authoring workspace
//   LensDesigner.runtimePosture();   // hide edit bay + show app bay
//   LensDesigner.whenReady(this, spawned, BookCoverView, function (v) {
//     v.title.text = 'Ready';        // runs once the controller has awoken
//   });
//
// The bays: '__LensDesignerEditBay__' holds the design-time workspace;
// '__LensDesignerAppBay__' holds your app content. Exactly one should be
// visible at a time - the designer swaps them on attach/detach, and the
// LDRuntimeGate component enforces runtime posture on device.

const LD_EDIT_BAY = '__LensDesignerEditBay__';
const LD_APP_BAY = '__LensDesignerAppBay__';

function ldFindRoot(name: string): SceneObject | null {
  const count = global.scene.getRootObjectsCount();
  for (let i = 0; i < count; i++) {
    const so = global.scene.getRootObject(i);
    if (so.name === name) return so;
  }
  return null;
}

function ldSetRootEnabled(name: string, enabled: boolean): void {
  const so = ldFindRoot(name);
  if (so) so.enabled = enabled;
}

export const LensDesigner = {
  /** Hide the design-time workspace ('__LensDesignerEditBay__'). */
  hideEditBay(): void { ldSetRootEnabled(LD_EDIT_BAY, false); },
  /** Show the design-time workspace. */
  showEditBay(): void { ldSetRootEnabled(LD_EDIT_BAY, true); },
  /** Hide the app-content root ('__LensDesignerAppBay__'). */
  hideAppBay(): void { ldSetRootEnabled(LD_APP_BAY, false); },
  /** Show the app-content root. */
  showAppBay(): void { ldSetRootEnabled(LD_APP_BAY, true); },
  /** Runtime posture: edit bay hidden, app bay shown. What a shipped lens wants. */
  runtimePosture(): void {
    ldSetRootEnabled(LD_EDIT_BAY, false);
    ldSetRootEnabled(LD_APP_BAY, true);
  },
  /** Design posture: edit bay shown, app bay hidden. The designer's mode. */
  designPosture(): void {
    ldSetRootEnabled(LD_EDIT_BAY, true);
    ldSetRootEnabled(LD_APP_BAY, false);
  },

  /**
   * Run cb once a spawned prefab's generated controller is initialized.
   * A freshly instantiated prefab runs its controller's onAwake a few frames
   * later, so getComponent returns null at first - this polls per frame
   * (default ~120 frames / 2s timeout) so consumers don't hand-roll the loop.
   *
   *   LensDesigner.whenReady(this, obj, BookCoverView, function (v) { ... });
   *
   * The controller's HANDLES (your bound slots) are created in its onAwake,
   * which can land a frame after the component itself exists - pass 'isReady'
   * to also gate on a slot when you touch handles immediately:
   *
   *   LensDesigner.whenReady(this, obj, BookspineView,
   *     function (v) { v.title.text = 'Ready'; },
   *     function (v) { return !!(v.title && v.background); });
   *
   * 'host' is the calling component (the UpdateEvent has to live somewhere).
   */
  whenReady: function <T>(
    host: BaseScriptComponent,
    obj: SceneObject,
    cls: { getTypeName(): string },
    cb: (c: T) => void,
    isReady?: (c: T) => boolean,
    timeoutFrames?: number,
  ): void {
    const max = timeoutFrames === undefined ? 120 : timeoutFrames;
    let tries = 0;
    const ev = host.createEvent('UpdateEvent');
    ev.bind(function () {
      const c = obj.getComponent(cls.getTypeName() as any) as unknown as T | null;
      if (c && (isReady === undefined || isReady(c))) { ev.enabled = false; cb(c); return; }
      tries++;
      if (tries > max) {
        ev.enabled = false;
        print('[LensDesigner] whenReady timed out waiting for ' + cls.getTypeName());
      }
    });
  },
};
`;

export const LD_RUNTIME_GATE_SRC = `import { LensDesigner } from './LensDesigner';

// LDRuntimeGate (generated by Lens Designer - do not edit).
//
// Attached by the designer to both bay roots. On a real device it forces
// runtime posture at lens start - the edit bay (authoring workspace) is
// hidden and the app bay shown - even if the project was last saved in the
// middle of a design session. Inside the Lens Studio editor it does nothing:
// the designer (or its designer-off toggle) owns the posture there.
@component
export class LDRuntimeGate extends BaseScriptComponent {
  onAwake(): void {
    if (global.deviceInfoSystem.isEditor()) return;
    LensDesigner.runtimePosture();
  }
}
`;
