/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Window-relative capture region, in window points (top-left origin). */
export interface Region {
  x: number
  y: number
  width: number
  height: number
}
/** Bounds of a window in screen points. */
export interface WindowBounds {
  x: number
  y: number
  width: number
  height: number
}
/**
 * Enumerated window entry. `id` is an opaque, platform-specific source
 * identifier encoded as a string (CGWindowID on macOS, HWND on Windows,
 * portal session token on Linux/Wayland). The bridge never parses it.
 */
export interface WindowEntry {
  id: string
  pid: number
  ownerName: string
  title: string
  bounds: WindowBounds
  onscreen: boolean
}
/** Returned by `capture_source`. PNG bytes; no on-disk file involved. */
export interface CaptureResult {
  png: Buffer
  width: number
  height: number
  capturedAtMs: number
}
/**
 * What the host platform can do. The bridge queries this once at
 * startup and routes accordingly. Adding a platform with a new
 * combination of flags requires no caller changes (TD-15 rule 5).
 */
export interface PlatformCapabilities {
  /**
   * True if windows can be enumerated without user interaction.
   * False on Wayland (the portal flow drives selection).
   */
  canEnumerate: boolean
  /**
   * True if the capture API requires the user to pick a source via a
   * system dialog (portal).
   */
  requiresInteractivePick: boolean
  /** True if capturing pixels requires explicit OS permission grant. */
  requiresPermissionGrant: boolean
  /**
   * True if capture sessions are stateful (created once, reused per
   * source, must be released when done).
   */
  hasStatefulCaptureSession: boolean
}
/**
 * Returns the host platform's capabilities. The bridge queries this
 * once at startup to drive its UI routing.
 */
export declare function getPlatformCapabilities(): PlatformCapabilities
/**
 * Enumerate windows owned by processes named "Lens Studio".
 * Returns [] on platforms where `can_enumerate == false`.
 */
export declare function enumerateLensStudioWindows(): Array<WindowEntry>
/**
 * Pick a Lens Studio source for capture. On platforms with
 * `requires_interactive_pick == false`, returns the auto-matched
 * window. On Wayland (v1.x), raises a portal dialog.
 */
export declare function pickLensStudioSource(): Promise<WindowEntry | null>
/** Capture a window-relative region as PNG. */
export declare function captureSource(id: string, region: Region): Promise<CaptureResult>
/**
 * Release any stateful capture resources held for this source.
 * No-op on stateless platforms (macOS v1.0).
 */
export declare function releaseSource(id: string): void
/** Resolve a listening TCP port to its owning PID, or null. */
export declare function portToPid(port: number): number | null
