// @lens-designer/bridge/client — browser-safe re-exports.
//
// The web app pulls in this entry to avoid bundling the node-only
// modules (screencap, mcp, window, applier, daemon) into the browser.
// Anything exported here MUST be free of node:* imports.

export {
  MANIFESTS,
  ALL_MANIFESTS,
  getManifest,
  RectangleManifest,
  TextManifest,
  PrimitiveManifestSchema,
  PropertyDescriptorSchema,
  SceneShapeNodeSchema,
  PropertyMappingSchema,
  type PrimitiveManifest,
  type PrimitiveCategory,
  type PropertyDescriptor,
  type PropertyKind,
  type SceneShapeNode,
  type ComponentKind,
  type PropertyMapping,
  type PropertyTransform,
  type ValueType as ManifestValueType,
} from './manifests/index.ts';

export {
  DesignNodeSchema,
  ServerToClientMsgSchema,
  ClientToServerMsgSchema,
  HelloMsgSchema,
  SandboxDownMsgSchema,
  DesignAppliedMsgSchema,
  DesignErrorMsgSchema,
  PreviewReadyMsgSchema,
  DesignApplyMsgSchema,
  PreviewConfigureRegionMsgSchema,
  WindowRegionSchema,
  Vec2Schema,
  Vec3Schema,
  Vec4Schema,
  InteractionSchema,
  InteractionRoleSchema,
  InteractionStateSchema,
  ColorStatesSchema,
  RgbaSchema,
  StatePropsSchema,
  StateOverridesSchema,
  STATE_PROP_KEYS,
  LayoutSpecSchema,
  ViewSchema,
  BindingSchema,
  type WindowRegion,
  type DesignNode,
  type Interaction,
  type InteractionRole,
  type InteractionState,
  type ColorStates,
  type Rgba,
  type Vec2,
  type StateProps,
  type StatePropKey,
  type StateOverrides,
  type LayoutSpec,
  type View,
  type Binding,
  type ServerToClientMsg,
  type ClientToServerMsg,
  type HelloMsg,
  type SandboxDownMsg,
  type DesignAppliedMsg,
  type DesignErrorMsg,
  type PreviewReadyMsg,
  type DesignApplyMsg,
  type PreviewConfigureRegionMsg,
  type Vec3,
  type Vec4,
  // attach-mode (Step 2 / 7)
  type TargetSummary,
  type ViewSummary,
  type GeneratedRef,
  type TargetListResultMsg,
  type AttachedMsg,
  type ViewSavedMsg,
  type ViewLoadedMsg,
  type ViewListResultMsg,
  type TargetListMsg,
  type TargetAttachMsg,
  type TargetDetachMsg,
  type TargetSetAssetsDirMsg,
  type ViewListMsg,
  type ViewLoadMsg,
  type ViewSaveMsg,
  type ViewDeleteMsg,
} from './protocol.ts';

// WB-L hug layout solver — pure, browser-safe; shared by the canvas preview.
export {
  computeHugLayout,
  type HugItem,
  type HugLayoutSpec,
  type HugBox,
  type HugResult,
} from './layout.ts';
