// codegen-gate.ts — emits the runtime Lens script that enforces RUNTIME
// posture on device (app bay on, edit bay off), while staying a no-op in the
// Lens Studio editor so the designer remains the editor-side authority.
//
// Generated-code rule: the EMITTED body must contain NO backticks and no
// `${` — a stray backtick in generated source has broken whole files before.
// This generator builds the source with plain string concatenation.

export const LD_RUNTIME_GATE_NAME = 'LDRuntimeGate';
export const LD_RUNTIME_GATE_FILENAME = 'LDRuntimeGate.ts';

export const EDIT_BAY_NAME = '__LensDesignerEditBay__';
export const APP_BAY_NAME = '__LensDesignerAppBay__';
export const OWNED_MARKER_NAME = '__LensDesignerOwned__';

/** Emit the LDRuntimeGate runtime script source. */
export function generateRuntimeGate(): string {
  const lines = [
    '// Generated by Lens Designer — do not edit (regenerated on connect).',
    '// On device this enforces runtime posture: the app bay is shown and the',
    '// edit bay is hidden. In the Lens Studio editor it is a no-op, so the',
    '// designer stays the editor-side authority over which bay is visible.',
    '',
    'const EDIT_BAY = "' + EDIT_BAY_NAME + '";',
    'const APP_BAY = "' + APP_BAY_NAME + '";',
    '',
    '@component',
    'export class ' + LD_RUNTIME_GATE_NAME + ' extends BaseScriptComponent {',
    '  onAwake() {',
    '    if (global.deviceInfoSystem.isEditor()) {',
    '      return;',
    '    }',
    '    const scene = global.scene;',
    '    const count = scene.getRootObjectsCount();',
    '    for (let i = 0; i < count; i++) {',
    '      const obj = scene.getRootObject(i);',
    '      if (obj.name === EDIT_BAY) {',
    '        obj.enabled = false;',
    '      } else if (obj.name === APP_BAY) {',
    '        obj.enabled = true;',
    '      }',
    '    }',
    '  }',
    '}',
    '',
  ];
  return lines.join('\n');
}
